name: Delete preview repository

on:
    pull_request:
        types: [closed]

jobs:
    delete-preview:
        permissions: write-all
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout files
              uses: actions/checkout@v4

            - name: Get preview repo name
              uses: ./.github/actions/get_preview_repo
              id: preview_repo

            - name: Wait for preview GitHub Pages
              continue-on-error: true
              run: >
                  timeout 300s bash -c '
                    until curl -I -f --no-progress-meter "$URL"; do
                      sleep 10;
                    done
                  '
              env:
                  URL: ${{ steps.preview_repo.outputs.gh_page_url }}

            - name: Delete preview repo
              uses: octokit/request-action@v2.x
              with:
                  route: DELETE /repos/{owner}/{repo_name}
                  accept: 'application/vnd.github+json'
                  owner: ${{ steps.preview_repo.outputs.owner }}
                  repo_name: ${{ steps.preview_repo.outputs.name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.DELREPO }}
